# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动用户的id')),
                ('sid', models.IntegerField(verbose_name='被滑动用户的id')),
                ('s_type', models.CharField(choices=[('dislike', '左滑'), ('like', '右滑'), ('superlike', '上滑')], max_length=12, verbose_name='滑动类型')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='滑动时间')),
            ],
            options={
                'db_table': 'swiped',
            },
        ),
    ]
