# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import libs.orm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('wh', '芜湖'), ('sz', '深圳'), ('wh', '武汉'), ('cd', '成都')], max_length=8, verbose_name='⽬标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('dating_sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='匹配的性别')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最⼤查找范围')),
                ('min_dating_age', models.IntegerField(default=22, verbose_name='最⼩交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最⼤交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让为匹配的⼈看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='⾃动播放视频')),
            ],
            options={
                'db_table': 'profile',
            },
            bases=(models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=14, unique=True, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(default=2000, verbose_name='出生年份')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出生月份')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出生日')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
                ('location', models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('wh', '芜湖'), ('sz', '深圳'), ('wh', '武汉'), ('cd', '成都')], max_length=8, verbose_name='长居地')),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model),
        ),
    ]
