# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('ah', '安徽'), ('sz', '深圳'), ('wh', '武汉'), ('cd', '成都')], max_length=8, verbose_name='⽬标城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, verbose_name='个人形象的url'),
        ),
    ]
