# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=14, unique=True, verbose_name='手机号码'),
        ),
    ]
