# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200816_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='权限的id'),
            preserve_default=False,
        ),
    ]
