# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_vip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='权限的id'),
        ),
    ]
